[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-config-file
[tool.pyright]
include = ["cvelib", "tests"]
exclude = ["**/__pycache__"]
venvPath = "./"
venv = ".venv"
