#!/usr/bin/python3
#
# SPDX-License-Identifier: MIT

import sys
import unittest

suite = unittest.TestLoader().discover("./tests", "test*.py", "./")
test_result = unittest.TextTestRunner(verbosity=2).run(suite)
if (
    len(test_result.errors) > 0
    or len(test_result.failures) > 0
    or len(test_result.unexpectedSuccesses) > 0
):  # pragma: nocover
    sys.exit(1)
