version: 2.1

commands:
  cache_restore:
    description: Restore python cache
    steps:
      - restore_cache:
          name: Restore python cache
          key: deps1-{{ .Branch }}-{{ checksum "setup.cfg" }}

  cache_save:
    description: Save python cache
    steps:
      - save_cache:
          name: Save python cache
          key: deps1-{{ .Branch }}-{{ checksum "setup.cfg" }}
          paths:
            - ".venv"

  python_components:
    description: Install python components
    steps:
      - run:
          name: Install python components
          command: |
            make setup-venv

  # https://docs.getwoke.tech/installation/
  install_woke:
    description: Install woke non-inclusivity checker
    steps:
      - run:
          description: Install woke non-inclusivity checker
          command: |
            go install github.com/get-woke/woke@v0.19.0

jobs:
  tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - cache_restore
      - python_components
      - run:
          name: Running coverage
          command: |
            . .venv/bin/activate
            make coverage
            make coverage-report
      - cache_save

  lint:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - cache_restore
      - python_components
      - run:
          name: Running syntax checks
          command: |
            . .venv/bin/activate
            make syntax-check
      - cache_save

  fmt:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - cache_restore
      - python_components
      - run:
          name: Running style checks
          command: |
            . .venv/bin/activate
            make style-check
      - cache_save

  inclusivity:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - install_woke
      - run:
          name: Running inclusivity checks
          command: |
            make inclusivity-check

# workflows can run in parallel
workflows:
  version: 2
  ci:
    jobs:
      - tests
      - lint
      - fmt
      - inclusivity
