version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Running coverage
          command: |
            . venv/bin/activate
            make coverage
            make coverage-report
      - run:
          name: Running syntax checks
          command: |
            . venv/bin/activate
            make syntax-check
      - run:
          name: Running style checks
          command: |
            . venv/bin/activate
            make style-check
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
