#!/bin/sh
#
# Copyright (c) 2021-2023 InfluxData
#
# Permission is hereby granted, free of charge, to any
# person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the
# Software without restriction, including without
# limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice
# shall be included in all copies or substantial portions
# of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF
# ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
# TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
set -e

exe=
args=
case "$1" in
    flake8)
        exe="$1"
        ;;
    black)
        exe="$1"
        # for now, only check
        args="--check --diff --quiet"
        ;;
    pylint3|pylint)
        exe="$1"
        # for now, only errors
        args="-E --disable=no-member"
        ;;
    *)
        echo "run-helper black|flake8|pylint3|pylint"
        exit 1
        ;;
esac

echo "= $exe ="
for i in ./cvelib/*py \
         ./bin/cve-* \
         ./bin/gar-report \
         ./bin/gh-report \
         ./bin/quay-report ; do
    # this is a bash script
    if [ "$i" = "./bin/cve-edit" ] || [ "$i" = "./bin/cve-nfu" ]; then
        continue
    fi

    echo "Checking $i"
    #shellcheck disable=2086
    PYTHONPATH=./ "$exe" $args "$i"
done
