---
name: "Semantic PR and Commit Messages"
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  semantic:
    uses: influxdata/validate-semantic-github-messages/.github/workflows/semantic.yml@main
